[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci --include=dev", "cd backend && npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.deploy]
cmds = ["cd backend && NODE_ENV=production node server.js"]

[start]
cmd = "cd backend && NODE_ENV=production node server.js"
